/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/buy-crypto`; params?: Router.UnknownInputParams; } | { pathname: `/buy`; params?: Router.UnknownInputParams; } | { pathname: `/collection-details`; params?: Router.UnknownInputParams; } | { pathname: `/connect-binance`; params?: Router.UnknownInputParams; } | { pathname: `/ethereum-charts`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/import`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mentor`; params?: Router.UnknownInputParams; } | { pathname: `/my-nft`; params?: Router.UnknownInputParams; } | { pathname: `/nfts`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/receive`; params?: Router.UnknownInputParams; } | { pathname: `/saque-pix`; params?: Router.UnknownInputParams; } | { pathname: `/sell-nft`; params?: Router.UnknownInputParams; } | { pathname: `/sell`; params?: Router.UnknownInputParams; } | { pathname: `/swap`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/buy-crypto`; params?: Router.UnknownOutputParams; } | { pathname: `/buy`; params?: Router.UnknownOutputParams; } | { pathname: `/collection-details`; params?: Router.UnknownOutputParams; } | { pathname: `/connect-binance`; params?: Router.UnknownOutputParams; } | { pathname: `/ethereum-charts`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/import`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mentor`; params?: Router.UnknownOutputParams; } | { pathname: `/my-nft`; params?: Router.UnknownOutputParams; } | { pathname: `/nfts`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/receive`; params?: Router.UnknownOutputParams; } | { pathname: `/saque-pix`; params?: Router.UnknownOutputParams; } | { pathname: `/sell-nft`; params?: Router.UnknownOutputParams; } | { pathname: `/sell`; params?: Router.UnknownOutputParams; } | { pathname: `/swap`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/buy-crypto${`?${string}` | `#${string}` | ''}` | `/buy${`?${string}` | `#${string}` | ''}` | `/collection-details${`?${string}` | `#${string}` | ''}` | `/connect-binance${`?${string}` | `#${string}` | ''}` | `/ethereum-charts${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/import${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mentor${`?${string}` | `#${string}` | ''}` | `/my-nft${`?${string}` | `#${string}` | ''}` | `/nfts${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/receive${`?${string}` | `#${string}` | ''}` | `/saque-pix${`?${string}` | `#${string}` | ''}` | `/sell-nft${`?${string}` | `#${string}` | ''}` | `/sell${`?${string}` | `#${string}` | ''}` | `/swap${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/buy-crypto`; params?: Router.UnknownInputParams; } | { pathname: `/buy`; params?: Router.UnknownInputParams; } | { pathname: `/collection-details`; params?: Router.UnknownInputParams; } | { pathname: `/connect-binance`; params?: Router.UnknownInputParams; } | { pathname: `/ethereum-charts`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/import`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mentor`; params?: Router.UnknownInputParams; } | { pathname: `/my-nft`; params?: Router.UnknownInputParams; } | { pathname: `/nfts`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/receive`; params?: Router.UnknownInputParams; } | { pathname: `/saque-pix`; params?: Router.UnknownInputParams; } | { pathname: `/sell-nft`; params?: Router.UnknownInputParams; } | { pathname: `/sell`; params?: Router.UnknownInputParams; } | { pathname: `/swap`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
